---
mysql_root_password: "{{ lookup('env', 'ANSIBLE_MYSQL_ROOT_PWD') }}"
mysql_socket: /var/run/mysqld/mysqld.sock
wsrep_cluster_address_primary: gcomm://
wsrep_cluster_address_additional: gcomm://10.10.10.31,10.10.10.30,10.10.10.29

# More detailed description of parameters - https://itproblog.ru/%d0%be%d0%bf%d1%82%d0%b8%d0%bc%d0%b8%d0%b7%d0%b0%d1%86%d0%b8%d1%8f-mysql-%d1%81%d0%b5%d1%80%d0%b2%d0%b5%d1%80%d0%b0-%d1%87%d0%b0%d1%81%d1%82%d1%8c-3-%d0%b1%d0%b0%d0%b7%d0%be%d0%b2%d0%b0%d1%8f-%d0%ba/
innodb_buffer_pool_size: 2G
max_connections: 300
thread_cache_size: 30
table_open_cache: 2000