---
# List of allowed TCP ports
# Galera Cluster firewall rules - https://galeracluster.com/library/documentation/firewall-settings.html
allowed_tcp_ports:
  - 22
  - 80
  - 3306
  - 10050
  - 4567
  - 4568
  - 4444

# List of allowed UDP ports
allowed_udp_ports:
  - 161