---
- name: (Ubuntu) Download repository install package
  get_url:
    url: "{{ zabbix_repo_package_url_ubuntu }}"
    dest: /tmp
  register: source_file_ubuntu
  when: ansible_os_family == 'Debian'

- name: (Ubuntu) Install Zabbix repository package
  apt:
    deb: "{{ source_file_ubuntu.dest }}"
  when: ansible_os_family == 'Debian'

- name: (Ubuntu) Install Zabbix Agent 2
  apt:
    name:
    - zabbix-agent2
    - zabbix-agent2-plugin-*
    state: present
  when: ansible_os_family == 'Debian'

- name: Restart and enable Zabbix Agent
  service:
    name: zabbix-agent2
    state: restarted
    enabled: true

- name: Add Zabbix server address to agent configuration file
  lineinfile:
    line: Server="{{ zabbix_server_ip }}"
    path: /etc/zabbix/zabbix_agent2.conf
    regexp: '^#?Server='